### ISSUE TITLE
there is nothing showed in vrep when i do "./run_sim.sh -t 400"

### ISSUE THREAD

**Issue by Yinghui-Lee** [MathiasThor/CPG-RBFN-framework#1]
I followed all the instruction and there is nothing wrong, but there is nothing showed in vrep when i do "./run_sim.sh -t 400". My environment is melodic, so i have no idea what's wrong or should it  be that?

**Comment by Yinghui-Lee** [comment]
it seems like that i could not load the environment when i input "./coppeliaSim.sh /media/liyinghui/My Passport
/个人资料/ubuntu/MachineLearning/CPG-RBFN-framework/simulations/MORF_pipe_behavior.ttt" in terminal. So is there anything i can do?

**Comment by Yinghui-Lee** [comment]
this is what i get in terminal when i input:./coppeliaSim.sh /media/liyinghui/My Passport
/个人资料/ubuntu/MachineLearning/CPG-RBFN-framework/simulations/MORF_pipe_behavior.ttt

[CoppeliaSimClient]    loading the CoppeliaSim library...
[CoppeliaSimClient]    done.
[CoppeliaSimClient:loadinfo]   launching CoppeliaSim...
[CoppeliaSim:loadinfo]   CoppeliaSim V4.1.0., (rev. 1), flavor: 1
[CoppeliaSim:loadinfo]   Legacy machine ID: 5000-9DEB-FFC4-9CEC-F7E3-841D
[CoppeliaSim:loadinfo]   Machine ID: 8F76-736C-7C50-0000-3C52-0101
[CoppeliaSim:loadinfo]   using the default Lua library.
[CoppeliaSim:loadinfo]   loaded the video compression library.
[CoppeliaSim:loadinfo]   if CoppeliaSim crashes now, try to install libgl1-mesa-dev on your system:
        >sudo apt install libgl1-mesa-dev
[CoppeliaSim:loadinfo]   OpenGL NVIDIA Corporation, Renderer: NVIDIA GeForce GTX 1050 Ti/PCIe/SSE2, Version: 4.6.0 NVIDIA 470.103.01
[CoppeliaSim:loadinfo]   simulator launched.
[CoppeliaSim:loadinfo]   plugin 'DynamicsBullet-2-78': loading...
[CoppeliaSim:loadinfo]   plugin 'DynamicsBullet-2-78': load succeeded.
[CoppeliaSim:loadinfo]   plugin 'DynamicsBullet-2-83': loading...
[CoppeliaSim:loadinfo]   plugin 'DynamicsBullet-2-83': load succeeded.
[CoppeliaSim:loadinfo]   plugin 'DynamicsNewton': loading...
[CoppeliaSim:loadinfo]   plugin 'DynamicsNewton': load succeeded.
[CoppeliaSim:loadinfo]   plugin 'DynamicsOde': loading...
[CoppeliaSim:loadinfo]   plugin 'DynamicsOde': load succeeded.
[CoppeliaSim:loadinfo]   plugin 'DynamicsVortex': loading...
[CoppeliaSim:loadinfo]   plugin 'DynamicsVortex': load succeeded.
[CoppeliaSim:loadinfo]   plugin 'Geometric': loading...
[CoppeliaSim:loadinfo]   plugin 'Geometric': load succeeded.
[CoppeliaSim:loadinfo]   plugin 'RosInterface': loading...
Plugin 'RosInterface': warning: replaced variable 'simROS'
[CoppeliaSim:loadinfo]   plugin 'RosInterface': load succeeded.
[CoppeliaSim:loadinfo]   plugin 'Assimp': loading...
[CoppeliaSim:loadinfo]   plugin 'Assimp': load succeeded.
[CoppeliaSim:loadinfo]   plugin 'BlueZero': loading...
[CoppeliaSim:loadinfo]   plugin 'BlueZero': load succeeded.
[CoppeliaSim:loadinfo]   plugin 'BubbleRob': loading...
[CoppeliaSim:loadinfo]   plugin 'BubbleRob': load succeeded.
[CoppeliaSim:loadinfo]   plugin 'Bwf': loading...
[CoppeliaSim:loadinfo]   plugin 'Bwf': load succeeded.
[CoppeliaSim:loadinfo]   plugin 'CodeEditor': loading...
[simExtCodeEditor:loadinfo]   CodeEditor plugin initialized
[CoppeliaSim:loadinfo]   plugin 'CodeEditor': load succeeded.
[CoppeliaSim:loadinfo]   plugin 'Collada': loading...
[CoppeliaSim:loadinfo]   plugin 'Collada': load succeeded.
[CoppeliaSim:loadinfo]   plugin 'ConvexDecompose': loading...
[CoppeliaSim:loadinfo]   plugin 'ConvexDecompose': load succeeded.
[CoppeliaSim:loadinfo]   plugin 'CustomUI': loading...
[CoppeliaSim:loadinfo]   plugin 'CustomUI': load succeeded.
[CoppeliaSim:loadinfo]   plugin 'ExternalRenderer': loading...
[CoppeliaSim:loadinfo]   plugin 'ExternalRenderer': load succeeded.
[CoppeliaSim:loadinfo]   plugin 'GLTF': loading...
[CoppeliaSim:loadinfo]   plugin 'GLTF': load succeeded.
[CoppeliaSim:loadinfo]   plugin 'ICP': loading...
[CoppeliaSim:loadinfo]   plugin 'ICP': load succeeded.
[CoppeliaSim:loadinfo]   plugin 'IK': loading...
[CoppeliaSim:loadinfo]   plugin 'IK': load succeeded.
[CoppeliaSim:loadinfo]   plugin 'Image': loading...
[CoppeliaSim:loadinfo]   plugin 'Image': load succeeded.
[CoppeliaSim:loadinfo]   plugin 'K3': loading...
[CoppeliaSim:loadinfo]   plugin 'K3': load succeeded.
[CoppeliaSim:loadinfo]   plugin 'LuaCommander': loading...
[CoppeliaSim:loadinfo]   plugin 'LuaCommander': load succeeded.
[CoppeliaSim:loadinfo]   plugin 'LuaRemoteApiClient': loading...
[CoppeliaSim:loadinfo]   plugin 'LuaRemoteApiClient': load succeeded.
[CoppeliaSim:loadinfo]   plugin 'Mtb': loading...
[CoppeliaSim:loadinfo]   plugin 'Mtb': load succeeded.
[CoppeliaSim:loadinfo]   plugin 'OMPL': loading...
[CoppeliaSim:loadinfo]   plugin 'OMPL': load succeeded.
[CoppeliaSim:loadinfo]   plugin 'OpenGL3Renderer': loading...
[CoppeliaSim:loadinfo]   plugin 'OpenGL3Renderer': load succeeded.
[CoppeliaSim:loadinfo]   plugin 'OpenMesh': loading...
[CoppeliaSim:loadinfo]   plugin 'OpenMesh': load succeeded.
[CoppeliaSim:loadinfo]   plugin 'Qhull': loading...
[CoppeliaSim:loadinfo]   plugin 'Qhull': load succeeded.
[CoppeliaSim:loadinfo]   plugin 'ROSInterface': loading...
[simExtROSInterface:warning]   replaced variable 'simROS'
[simExtROSInterface:warning]   replaced function 'simROS.subscribe@ROSInterface'
[simExtROSInterface:warning]   replaced function 'simROS.shutdownSubscriber@ROSInterface'
[simExtROSInterface:warning]   replaced function 'simROS.subscriberTreatUInt8ArrayAsString@ROSInterface'
[simExtROSInterface:warning]   replaced function 'simROS.advertise@ROSInterface'
[simExtROSInterface:warning]   replaced function 'simROS.shutdownPublisher@ROSInterface'
[simExtROSInterface:warning]   replaced function 'simROS.publisherTreatUInt8ArrayAsString@ROSInterface'
[simExtROSInterface:warning]   replaced function 'simROS.publish@ROSInterface'
[simExtROSInterface:warning]   replaced function 'simROS.serviceClient@ROSInterface'
[simExtROSInterface:warning]   replaced function 'simROS.shutdownServiceClient@ROSInterface'
[simExtROSInterface:warning]   replaced function 'simROS.serviceClientTreatUInt8ArrayAsString@ROSInterface'
[simExtROSInterface:warning]   replaced function 'simROS.call@ROSInterface'
[simExtROSInterface:warning]   replaced function 'simROS.advertiseService@ROSInterface'
[simExtROSInterface:warning]   replaced function 'simROS.shutdownServiceServer@ROSInterface'
[simExtROSInterface:warning]   replaced function 'simROS.serviceServerTreatUInt8ArrayAsString@ROSInterface'
[simExtROSInterface:warning]   replaced function 'simROS.sendTransform@ROSInterface'
[simExtROSInterface:warning]   replaced function 'simROS.sendTransforms@ROSInterface'
[simExtROSInterface:warning]   replaced function 'simROS.imageTransportSubscribe@ROSInterface'
[simExtROSInterface:warning]   replaced function 'simROS.imageTransportShutdownSubscriber@ROSInterface'
[simExtROSInterface:warning]   replaced function 'simROS.imageTransportAdvertise@ROSInterface'
[simExtROSInterface:warning]   replaced function 'simROS.imageTransportShutdownPublisher@ROSInterface'
[simExtROSInterface:warning]   replaced function 'simROS.imageTransportPublish@ROSInterface'
[simExtROSInterface:warning]   replaced function 'simROS.getTime@ROSInterface'
[simExtROSInterface:warning]   replaced function 'simROS.getParamString@ROSInterface'
[simExtROSInterface:warning]   replaced function 'simROS.getParamInt@ROSInterface'
[simExtROSInterface:warning]   replaced function 'simROS.getParamDouble@ROSInterface'
[simExtROSInterface:warning]   replaced function 'simROS.getParamBool@ROSInterface'
[simExtROSInterface:warning]   replaced function 'simROS.setParamString@ROSInterface'
[simExtROSInterface:warning]   replaced function 'simROS.setParamInt@ROSInterface'
[simExtROSInterface:warning]   replaced function 'simROS.setParamDouble@ROSInterface'
[simExtROSInterface:warning]   replaced function 'simROS.setParamBool@ROSInterface'
[simExtROSInterface:warning]   replaced function 'simROS.hasParam@ROSInterface'
[simExtROSInterface:warning]   replaced function 'simROS.deleteParam@ROSInterface'
[simExtROSInterface:warning]   replaced function 'simROS.searchParam@ROSInterface'
[CoppeliaSim:loadinfo]   plugin 'ROSInterface': load succeeded.
[CoppeliaSim:loadinfo]   plugin 'RRS1': loading...
[CoppeliaSim:loadinfo]   plugin 'RRS1': load succeeded.
[CoppeliaSim:loadinfo]   plugin 'ReflexxesTypeII': loading...
[CoppeliaSim:loadinfo]   plugin 'ReflexxesTypeII': load succeeded.
[CoppeliaSim:loadinfo]   plugin 'RemoteApi': loading...
[simExtRemoteApi:loadinfo]   starting a remote API server on port 19997
[CoppeliaSim:loadinfo]   plugin 'RemoteApi': load succeeded.
[CoppeliaSim:loadinfo]   plugin 'SDF': loading...
[CoppeliaSim:loadinfo]   plugin 'SDF': load succeeded.
[CoppeliaSim:loadinfo]   plugin 'SurfaceReconstruction': loading...
[CoppeliaSim:loadinfo]   plugin 'SurfaceReconstruction': load succeeded.
[CoppeliaSim:loadinfo]   plugin 'URLDrop': loading...
[CoppeliaSim:loadinfo]   plugin 'URLDrop': load succeeded.
[CoppeliaSim:loadinfo]   plugin 'Urdf': loading...
[CoppeliaSim:loadinfo]   plugin 'Urdf': load succeeded.
[CoppeliaSim:loadinfo]   plugin 'Vision': loading...
[CoppeliaSim:loadinfo]   plugin 'Vision': load succeeded.
[CoppeliaSim:loadinfo]   using the 'Geometric' plugin.
[CoppeliaSim:loadinfo]   using the 'IK' plugin.
[simExtDynamicsVortex:loadinfo]   2020.3.0.68
[CoppeliaSim:loadinfo]   plugin 'DynamicsBullet-2-78': unloading...
[CoppeliaSim:loadinfo]   plugin 'DynamicsBullet-2-78': done.
[CoppeliaSim:loadinfo]   plugin 'DynamicsBullet-2-83': unloading...
[CoppeliaSim:loadinfo]   plugin 'DynamicsBullet-2-83': done.
[CoppeliaSim:loadinfo]   plugin 'DynamicsNewton': unloading...
[CoppeliaSim:loadinfo]   plugin 'DynamicsNewton': done.
[CoppeliaSim:loadinfo]   plugin 'DynamicsOde': unloading...
[CoppeliaSim:loadinfo]   plugin 'DynamicsOde': done.
[CoppeliaSim:loadinfo]   plugin 'DynamicsVortex': unloading...
[CoppeliaSim:loadinfo]   plugin 'DynamicsVortex': done.
[CoppeliaSim:loadinfo]   plugin 'Geometric': unloading...
[CoppeliaSim:loadinfo]   plugin 'Geometric': done.
[CoppeliaSim:loadinfo]   plugin 'RosInterface': unloading...
[CoppeliaSim:loadinfo]   plugin 'RosInterface': done.
[CoppeliaSim:loadinfo]   plugin 'Assimp': unloading...
[CoppeliaSim:loadinfo]   plugin 'Assimp': done.
[CoppeliaSim:loadinfo]   plugin 'BlueZero': unloading...
[CoppeliaSim:loadinfo]   plugin 'BlueZero': done.
[CoppeliaSim:loadinfo]   plugin 'BubbleRob': unloading...
[CoppeliaSim:loadinfo]   plugin 'BubbleRob': done.
[CoppeliaSim:loadinfo]   plugin 'Bwf': unloading...
[CoppeliaSim:loadinfo]   plugin 'Bwf': done.
[CoppeliaSim:loadinfo]   plugin 'CodeEditor': unloading...
[CoppeliaSim:loadinfo]   plugin 'CodeEditor': done.
[CoppeliaSim:loadinfo]   plugin 'Collada': unloading...
[CoppeliaSim:loadinfo]   plugin 'Collada': done.
[CoppeliaSim:loadinfo]   plugin 'ConvexDecompose': unloading...
[CoppeliaSim:loadinfo]   plugin 'ConvexDecompose': done.
[CoppeliaSim:loadinfo]   plugin 'CustomUI': unloading...
[CoppeliaSim:loadinfo]   plugin 'CustomUI': done.
[CoppeliaSim:loadinfo]   plugin 'ExternalRenderer': unloading...
[CoppeliaSim:loadinfo]   plugin 'ExternalRenderer': done.
[CoppeliaSim:loadinfo]   plugin 'GLTF': unloading...
[CoppeliaSim:loadinfo]   plugin 'GLTF': done.
[CoppeliaSim:loadinfo]   plugin 'ICP': unloading...
[CoppeliaSim:loadinfo]   plugin 'ICP': done.
[CoppeliaSim:loadinfo]   plugin 'IK': unloading...
[CoppeliaSim:loadinfo]   plugin 'IK': done.
[CoppeliaSim:loadinfo]   plugin 'Image': unloading...
[CoppeliaSim:loadinfo]   plugin 'Image': done.
[CoppeliaSim:loadinfo]   plugin 'K3': unloading...
[CoppeliaSim:loadinfo]   plugin 'K3': done.
[CoppeliaSim:loadinfo]   plugin 'LuaCommander': unloading...
[CoppeliaSim:loadinfo]   plugin 'LuaCommander': done.
[CoppeliaSim:loadinfo]   plugin 'LuaRemoteApiClient': unloading...
[CoppeliaSim:loadinfo]   plugin 'LuaRemoteApiClient': done.
[CoppeliaSim:loadinfo]   plugin 'Mtb': unloading...
[CoppeliaSim:loadinfo]   plugin 'Mtb': done.
[CoppeliaSim:loadinfo]   plugin 'OMPL': unloading...
[CoppeliaSim:loadinfo]   plugin 'OMPL': done.
[CoppeliaSim:loadinfo]   plugin 'OpenGL3Renderer': unloading...
[CoppeliaSim:loadinfo]   plugin 'OpenGL3Renderer': done.
[CoppeliaSim:loadinfo]   plugin 'OpenMesh': unloading...
[CoppeliaSim:loadinfo]   plugin 'OpenMesh': done.
[CoppeliaSim:loadinfo]   plugin 'Qhull': unloading...
[CoppeliaSim:loadinfo]   plugin 'Qhull': done.
[CoppeliaSim:loadinfo]   plugin 'ROSInterface': unloading...
[CoppeliaSim:loadinfo]   plugin 'ROSInterface': done.
[CoppeliaSim:loadinfo]   plugin 'RRS1': unloading...
[CoppeliaSim:loadinfo]   plugin 'RRS1': done.
[CoppeliaSim:loadinfo]   plugin 'ReflexxesTypeII': unloading...
[CoppeliaSim:loadinfo]   plugin 'ReflexxesTypeII': done.
[CoppeliaSim:loadinfo]   plugin 'RemoteApi': unloading...
[CoppeliaSim:loadinfo]   plugin 'RemoteApi': done.
[CoppeliaSim:loadinfo]   plugin 'SDF': unloading...
[CoppeliaSim:loadinfo]   plugin 'SDF': done.
[CoppeliaSim:loadinfo]   plugin 'SurfaceReconstruction': unloading...
[CoppeliaSim:loadinfo]   plugin 'SurfaceReconstruction': done.
[CoppeliaSim:loadinfo]   plugin 'URLDrop': unloading...
[CoppeliaSim:loadinfo]   plugin 'URLDrop': done.
[CoppeliaSim:loadinfo]   plugin 'Urdf': unloading...
[CoppeliaSim:loadinfo]   plugin 'Urdf': done.
[CoppeliaSim:loadinfo]   plugin 'Vision': unloading...
[CoppeliaSim:loadinfo]   plugin 'Vision': done.

**Comment by needprotein** [comment]
请问，他安装里说的.zip文件是main那个包么，里面没有他的remote.txt呀
